proc_video('/home/weiliu89/playpen/part/data/sheep/sheep6', '/home/weiliu89/playpen/part/out/sheep/sheep6', 'VOC2009/sheep_final.mat', 5)
proc_video('/home/weiliu89/playpen/part/data/sheep/sheep7', '/home/weiliu89/playpen/part/out/sheep/sheep7', 'VOC2009/sheep_final.mat', 5)
proc_video('/home/weiliu89/playpen/part/data/sheep/sheep8', '/home/weiliu89/playpen/part/out/sheep/sheep8', 'VOC2009/sheep_final.mat', 5)
proc_video('/home/weiliu89/playpen/part/data/sheep/sheep9', '/home/weiliu89/playpen/part/out/sheep/sheep9', 'VOC2009/sheep_final.mat', 5)
proc_video('/home/weiliu89/playpen/part/data/sheep/sheep10', '/home/weiliu89/playpen/part/out/sheep/sheep10', 'VOC2009/sheep_final.mat', 5)
